version: '3'
services:
  client:
    image: alangulot.azurecr.io/client:latest
    ports:
       - "3000:3000"
       - "2222:2222"
    depends_on:
       - server
    environment:
       - apiURL=http://server:3001

  server:
    image: alangulot.azurecr.io/server:latest
    ports:
      - "3001:3001"